apiVersion: v1
kind: Pod
metadata:
  name: config-test-pod
spec:
  containers:
    - name: test-container
      image: busybox
      command: ["/bin/sh", "-c", "env"]
      env:
        - name: STUDENT_NAME
          valueFrom:
            configMapKeyRef:
              name: my-map
              key: student
        - name: SCHOOL 
          valueFrom:
            configMapKeyRef:
              name: my-map
              key: school
        - name: KUBERNETES
          valueFrom:
            configMapKeyRef:
              name: my-map
              key: kubernetes
  restartPolicy: Never
